[package]
name = "jsonrpc"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
chashmap = "2.2"
futures-boxed = { path = "../futures_boxed" }
futures-preview = { version = "0.3.0-alpha.18", features = ["compat"] }
runtime = "0.3.0-alpha.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
